import Head from 'next/head'
import Image from 'next/image'
import GridSection from '../components/GridSection'
import SubHero from '../components/SubHero'
import SubHero2 from '../components/Subhero2'
import SubHero3 from '../components/SubHero3'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
      <SubHero/>
      <SubHero2/>
      <SubHero3/>
      <GridSection/>
      </main>
    </div>
  )
}
